version: '3'

services:

  {{ cookiecutter.project_name }}-redis:
    image: redis:alpine
    restart: always
    ports:
      - "18111:6379"

  {{ cookiecutter.project_name }}-django-web:
    build: .
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      DB_HOST: {{ cookiecutter.project_name }}-django-db
      DB_NAME: {{ cookiecutter.project_name }}
      DB_USER: admin
      DB_PASSWORD: {{ cookiecutter.password }}
    volumes:
      - ./code:/code
      - ./datas:/datas
    ports:
      - 18100:8000
    depends_on:
      - tws-db

  {{ cookiecutter.project_name }}-django-db:
    image: postgres:latest
    restart: always
    command: >
      -c max_connections=1000
      -c work_mem=256MB
      -c shared_buffers=4GB
    ports:
      - 18112:5432
    environment:
      PGUSER: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: {{ cookiecutter.password }}
      POSTGRES_DB: {{ cookiecutter.password }}
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./datas:/datas
